name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run Tests
        run: |
          bundle install
          bundle exec rake spec
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3.1.0
